config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :quotes
  
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:author, :quotation, :source)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="w3-bar w3-light-blue">
     <div class="w3-sidebar w3-bar-block w3-border-right w3-light-blue" style="display:none" id="mySidebar">
      <button onclick="w3_close()" class="w3-bar-item w3-large">Close &times;</button>
        <a href="/static_pages/home" class="w3-bar-item w3-button">Home</a>
        <a href="/quotes" class="w3-bar-item w3-button">Quotes</a>
        <a href="/static_pages/help" class="w3-bar-item w3-button">Help</a>
        <a href="/static_pages/about" class="w3-bar-item w3-button">About</a>
     </div>

        <a href="/static_pages/home" class="w3-bar-item w3-button">Home</a>
        <a href="/quotes" class="w3-bar-item w3-button">Quotes</a>
        <a href="/static_pages/help" class="w3-bar-item w3-button">Help</a>
        <a href="/static_pages/about" class="w3-bar-item w3-button">About</a>
    </div>
    <%= yield %>
  </body>
  <script>
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
}
function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
}
</script>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :quote_author %>
  </div>

  <div class="field">
    <%= form.label :quotation %>
    <%= form.text_field :quotation, id: :quote_quotation %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :quote_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1 class="w3-center">Editing Quote</h1>
<hr>
<div>
  <div class="w3-light-blue w3-display-middle w3-center" style="width:20%">

<%= render 'form', quote: @quote %>
<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>
</div>
</div>
   

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="w3-center">Quotes</h1>

<input class="w3-input w3-border w3-padding" type="text" placeholder="Search for quotes.." id="myInput" onkeyup="myFunction()">
<table class="w3-table-all" id="myTable">
  <thead>
    <tr class="w3-light-blue">
      <th>Author</th>
      <th>Quotation</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.author %></td>
        <td><i>"<%= quote.quotation %>"</i></td>
        <td><%= quote.source %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="w3-bar w3-light-blue">
 <a href="/quotes/new" class="w3-left w3-button"> + New Quote</a>
</div>
<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

app/views/quotes/new.html.erb
<h1 class="w3-center">New Quote</h1>
<hr>
<div>
  <div class="w3-light-blue w3-display-middle w3-center" style="width:20%">
<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>
  </div>
</div>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="w3-container">
  <div class="w3-panel w3-leftbar w3-light-grey">
    <p class="w3-xlarge w3-serif"><strong>Quote:</strong><i>"<%= @quote.quotation %>"</i></p>
<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<p>
  <strong>Source:</strong>
  <%= @quote.source %>
</p>
  </div>
</div>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/static_pages/about.html.erb
<h1 class="w3-center">About</h1>
<hr>
<div  class="w3-display-middle" style="width:50%">
  <div class="w3-center"><strong>About the Site:</strong><br><br>This site is dedicated to the collection and creation of a quotation database for DePaul University's Web Development I (IT-231) class.<br>&nbsp;</div>
  <br><div class="w3-center w3-light-grey"><br>&nbsp;<strong>About Me: </strong><br><br>I am a Management Informational Systems major, minoring in electronic commerce technology.<br>&nbsp;<br>&nbsp;</div>
</div>

app/views/static_pages/help.html.erb
<h1 class="w3-center">Help</h1>
<hr>
<p class="w3-center">If you need help navigating the site or have any questions about its design, please contact the site's manager with the information provided below:</p>
<br> 

<header class="w3-container w3-light-grey w3 -center">
  <h3 class = "w3-center"><strong>Need help with the site?</strong></h3>
</header>

<div class="w3-container w3-center">
  <h4>Contact:</h4>
  <hr>
  <!--img src="helpCardPhoto.jpg" alt="Avatar" class="w3-left w3-circle"-->
  
  <p><strong>Madeline Honda</strong>
    <br>
    <em>MyQuotes, Site Manager</em>
  <br> 
    Cell: 651-955-6461
   <br> 
    Email: hondamade@gmail.com
  </p>
</div>

<a href="mailto:hondamade@gmail.com" class="w3-button w3-block w3-light-blue"> Send Email </a>

</div>

app/views/static_pages/home.html.erb
<h1 class="w3-center">Home</h1>
<hr>
<br>
<p class="w3-center">Welcome to MyQuotes Archive! Here you can archive any quotation you would like with proper citation. Add your favorite quote to the database now!</p>
<br><br>
<div class ="w3-bar w3-center">
  <a href="/quotes" class="w3-center w3-button w3-light-blue" style="width:40%">Get Started!</a>
</div>